In [8]:
import numpy as np
import pandas as pd

In [9]:
mat1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
mat2D = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [10]:
print(f"Matriks 1D:\n{mat1D}")
print(f"Matriks 1D indeks ke-7:\n{mat1D[7]}")
print(f"Matriks 1D * 10:\n{mat1D * 10}")

Matriks 1D:
[1 2 3 4 5 6 7 8 9]
Matriks 1D indeks ke-7:
8
Matriks 1D * 10:
[10 20 30 40 50 60 70 80 90]


In [11]:
print(f"Matriks 2D:\n{mat2D}")
print(f"Matriks 2D * 10:\n{mat2D * 10}")

Matriks 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks 2D * 10:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
print(f"Ukuran Matriks 1D:\n{mat1D.size}")
print(f"Ukuran Matriks 2D:\n{mat2D.size}")

Ukuran Matriks 1D:
9
Ukuran Matriks 2D:
9


In [13]:
mZero = np.zeros((3, 3))              
mOne = np.ones((3000, 3000))          
mFull = np.full((4, 4), 7)            
mIdentity = np.eye(4)               

# Cetak hasil
print("Matriks Nol (3x3):")
print(mZero)

print("\nMatriks Satu (3000x3000), ditampilkan sebagian:")
print(mOne[:3, :3]) 

print("\nMatriks Full (4x4) isi 7:")
print(mFull)

print("\nMatriks Identitas (4x4):")
print(mIdentity)

Matriks Nol (3x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matriks Satu (3000x3000), ditampilkan sebagian:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matriks Full (4x4) isi 7:
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

Matriks Identitas (4x4):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
np.random.seed(42)

jumlah_data = 100

daftar_gender = ['Male', 'Female']
daftar_pembayaran = ['Cash', 'Credit Card', 'E-Wallet']

data_gender = np.random.choice(daftar_gender, size=jumlah_data)
data_usia = np.random.randint(low=18, high=61, size=jumlah_data)
data_transaksi = np.random.randint(low=1, high=11, size=jumlah_data)
data_pembayaran = np.random.choice(daftar_pembayaran, size=jumlah_data)

data_dict = {
    'Gender': data_gender,
    'Usia': data_usia,
    'Transaksi': data_transaksi,
    'Pembayaran': data_pembayaran
}

df = pd.DataFrame(data_dict)

print("\nData Sample (10 Pertama):\n")
for i in range(10):
    print(f"Data ke-{i+1:2}: Gender = {df['Gender'][i]:6} | Usia = {df['Usia'][i]:2} "
          f"| Transaksi = {df['Transaksi'][i]:2} | Pembayaran = {df['Pembayaran'][i]}")

jumlah_baris = df.shape[0]
print(f"\nJumlah Total Data:\n{jumlah_baris} baris")

print("\nRingkasan Statistik:\n")
deskripsi = df.describe(include='all')
print(deskripsi)


Data Sample (10 Pertama):

Data ke- 1: Gender = Male   | Usia = 35 | Transaksi =  1 | Pembayaran = Cash
Data ke- 2: Gender = Female | Usia = 43 | Transaksi =  9 | Pembayaran = E-Wallet
Data ke- 3: Gender = Male   | Usia = 51 | Transaksi =  9 | Pembayaran = Cash
Data ke- 4: Gender = Male   | Usia = 27 | Transaksi =  4 | Pembayaran = Credit Card
Data ke- 5: Gender = Male   | Usia = 53 | Transaksi =  9 | Pembayaran = Credit Card
Data ke- 6: Gender = Female | Usia = 31 | Transaksi =  3 | Pembayaran = E-Wallet
Data ke- 7: Gender = Male   | Usia = 48 | Transaksi =  7 | Pembayaran = Credit Card
Data ke- 8: Gender = Male   | Usia = 32 | Transaksi =  6 | Pembayaran = Cash
Data ke- 9: Gender = Male   | Usia = 25 | Transaksi =  8 | Pembayaran = E-Wallet
Data ke-10: Gender = Female | Usia = 31 | Transaksi =  9 | Pembayaran = Cash

Jumlah Total Data:
100 baris

Ringkasan Statistik:

        Gender        Usia  Transaksi Pembayaran
count      100  100.000000  100.00000        100
unique       2    